---
- hosts: all
  become: yes
  pre_tasks:
    - name: include env vars
      include_vars: "../vars/{{ stackEnv }}/{{ stackInstName }}.yml"
      tags: ["always"]
  roles:
    #loads variables as per instance-name.yml for db tier

    - role: config_db_tns
      tags: config_db_tns
